// src/views/auth/Login.vue
<template>
  <div>
    <h1>Login</h1>
    <br />
    <div
      class="container text-center"
      style="
        max-width: 600px;
        background-color: grey;
        padding: 20px;
        border-radius: 8px;
      "
    >
      <form @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="username">Username</label>
          <input
            type="text"
            id="username"
            v-model="username"
            class="form-control"
          />
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            id="password"
            v-model="password"
            class="form-control"
          />
        </div>

        <br />

        <button
          type="submit"
          class="btn btn-light"
          style="background-color: #fdb14d"
        >
          Log in
        </button>

        <p style="color: red">{{ errorMessage }}</p>
      </form>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import service from "../../services/config";
import authContext from "../../context/auth.context";

export default {
  name: "Login",
  setup() {
    const username = ref("");
    const password = ref("");
    const errorMessage = ref("");
    const router = useRouter();

    const handleLogin = async () => {
      try {
        const credentials = {
          username: username.value,
          password: password.value,
        };
        const response = await service.post("/auth/login", credentials);
        localStorage.setItem("authToken", response.data.authToken);
        router.push("/");
      } catch (error) {
        if (error.response && error.response.status === 400) {
          errorMessage.value = error.response.data.errorMessage;
        } else {
          router.push("/error");
        }
      }
    };

    onMounted(() => {
      authContext.authenticateUser();
    });

    return {
      username,
      password,
      errorMessage,
      handleLogin,
      authContext,
    };
  },
};
</script>

<style>
.container {
  margin: 0 auto;
}
</style>

// src/pages/auth/Login.jsx
import { useContext, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import service from "../../services/config";
import { AuthContext } from "../../context/auth.context";

// Bootstrap
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import Container from "react-bootstrap/Container";

function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const { authenticateUser } = useContext(AuthContext);
  const redirect = useNavigate();

  const handleUsernameChange = (e) => setUsername(e.target.value);
  const handlePasswordChange = (e) => setPassword(e.target.value);
  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      const credentials = { username, password };
      const response = await service.post("/auth/login", credentials);

      localStorage.setItem("authToken", response.data.authToken);

      await authenticateUser();

      redirect("/");
    } catch (error) {
      if (error.response && error.response.status === 400) {
        setErrorMessage(error.response.data.errorMessage);
      } else {
        redirect("/error");
      }
    }
  };

  // Styles
  const containerStyle = {
    maxWidth: "600px",
    backgroundColor: "grey",
    padding: "20px",
    borderRadius: "8px",
  };

  return (
    <div>
      <h1>Log in</h1>
      <br />
      <Container className="text-center" style={containerStyle}>
        <Form onSubmit={handleLogin}>
          <Form.Group controlId="formUsername">
            <Form.Label>Username</Form.Label>
            <Form.Control
              type="text"
              name="username"
              value={username}
              onChange={handleUsernameChange}
            />
          </Form.Group>

          <Form.Group controlId="formPassword">
            <Form.Label>Password</Form.Label>
            <Form.Control
              type="password"
              name="password"
              value={password}
              onChange={handlePasswordChange}
            />
          </Form.Group>

          <br />

          <Button
            variant="light"
            type="submit"
            style={{ backgroundColor: "#fdb14d" }}
          >
            Enter
          </Button>
          <br />
          <br />
          <p>
            Are you still not registered yet?
            <Link to={"/register"}>click here!</Link>
          </p>
          <p style={{ color: "red" }}>{errorMessage}</p>
        </Form>
      </Container>
    </div>
  );
}

export default Login;
