// src/pages/auth/Register.jsx
import { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import service from "../../services/config";
import { AuthContext } from "../../context/auth.context";

// Bootstrap
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import Container from "react-bootstrap/Container";

function Register() {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const { authenticateUser } = useContext(AuthContext);
  const redirect = useNavigate();

  const handleUsernameChange = (e) => setUsername(e.target.value);
  const handleEmailChange = (e) => setEmail(e.target.value);
  const handlePasswordChange = (e) => setPassword(e.target.value);
  const handleSignup = async (e) => {
    e.preventDefault();
    const newUser = { username, email, password };
    try {
      await service.post("/auth/register", newUser);

      const credentials = { username, password };
      const response = await service.post("/auth/login", credentials);

      localStorage.setItem("authToken", response.data.authToken);

      await authenticateUser();

      redirect("/");
    } catch (error) {
      if (error.response && error.response.status === 400) {
        setErrorMessage(error.response.data.errorMessage);
      } else {
        redirect("/error");
      }
    }
  };

  // Styles
  const containerStyle = {
    maxWidth: "600px",
    backgroundColor: "grey",
    padding: "20px",
    borderRadius: "8px",
  };

  return (
    <div>
      <h1>Create your account</h1>
      <br />

      <Container className="text-center" style={containerStyle}>
        <Form onSubmit={handleSignup}>
          <Form.Group controlId="formUsername">
            <Form.Label>Username</Form.Label>
            <Form.Control
              type="text"
              name="username"
              value={username}
              onChange={handleUsernameChange}
            />
          </Form.Group>

          <Form.Group controlId="formEmail">
            <Form.Label>E-mail</Form.Label>
            <Form.Control
              type="email"
              name="email"
              value={email}
              onChange={handleEmailChange}
            />
          </Form.Group>

          <Form.Group controlId="formPassword">
            <Form.Label>Password</Form.Label>
            <Form.Control
              type="password"
              name="password"
              value={password}
              onChange={handlePasswordChange}
            />
          </Form.Group>

          <br />

          <Button
            variant="light"
            type="submit"
            style={{ backgroundColor: "#fdb14d" }}
          >
            Sign up
          </Button>

          <p style={{ color: "red" }}>{errorMessage}</p>
        </Form>
      </Container>
    </div>
  );
}

export default Register;

// src/views/auth/Register.vue
<template>
  <div>
    <h1>Create your account</h1>
    <br />

    <div
      class="container text-center"
      style="
        max-width: 600px;
        background-color: grey;
        padding: 20px;
        border-radius: 8px;
      "
    >
      <form @submit.prevent="handleSignup">
        <div class="form-group">
          <label for="username">Username</label>
          <input
            type="text"
            id="username"
            v-model="username"
            class="form-control"
          />
        </div>

        <div class="form-group">
          <label for="email">E-mail</label>
          <input type="email" id="email" v-model="email" class="form-control" />
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            id="password"
            v-model="password"
            class="form-control"
          />
        </div>

        <br />

        <button
          type="submit"
          class="btn btn-light"
          style="background-color: #fdb14d"
        >
          Sign up
        </button>

        <p style="color: red">{{ errorMessage }}</p>
      </form>
    </div>
  </div>
</template>

<script>
import { ref } from "vue";
import { useRoute } from "vue-router";
import service from "../../services/config";

export default {
  name: "Register",
  setup() {
    const username = ref("");
    const email = ref("");
    const password = ref("");
    const errorMessage = ref("");
    const route = useRoute();

    const handleSignup = async () => {
      const newUser = {
        username: username.value,
        email: email.value,
        passowrd: password.value,
      };

      try {
        await service.post("/auth/register", newUser);
        const credentials = {
          username: username.value,
          password: password.value,
        };
        const response = await service.post("/auth/login", credentials);
        localStorage.setItem("authToken", response.data.authToken);
        route.push("/");
      } catch (error) {
        if (error.response && error.response.status === 400) {
          errorMessage.value = error.response.data.errorMessage;
        } else {
          route.push("/error");
        }
      }
    };

    return {
      username,
      email,
      password,
      errorMessage,
      handleSignup,
    };
  },
};
</script>

<style>
.container {
  margin: 0 auto;
}
</style>
